#!/usr/bin/python
#!python
import glob
import os
os.chdir(".")

hasrm = False
#clean all files with given extention
for x in [".log","~",".pyc",".dot",".gps"]:
	for files in glob.glob("*"+x):
		os.unlink(files)
		print "removing "+files
		hasrm = True

#remove temp files (~) from subfolders
for root, dirnames, filenames in os.walk('.'):
	for fle in filenames:
		if(fle[len(fle)-1]=="~"):
			fname = root+"/"+fle 
			os.unlink(fname)
			print "removing "+fname
			hasrm = True

#clear build
#clear directory
for ff in glob.glob("build/*"):
	os.remove(ff)

#add README file in build if not present
fname = "build/README"
if(not(os.path.isfile(fname))):
	print "adding README in build"
	fout = open(fname,"w")
	fout.write("this folder will contains the built files\n")
	fout.close()

if(not(hasrm)): print "nothing to clean"
print "done!"
