#!/usr/bin/python
#!python
import sys,shutil,os,glob
from kromelib import *

#check number the of arguments
if(len(sys.argv)<2):
	die(get_usage())


#you can select only one -forceMF
if(("-forceMF=222" in sys.argv) and ("-forceMF=21" in sys.argv)):
	die("ERROR: options -forceMF=222 and -forceMF=21 are mutually exclusive: choose one.")
print

#set defaults
solver_MF = 222
force_rwork = useHeating = doReport = checkConserv = useFileIdx = buildCompact = useEquilibrium = False
use_implicit_RHS = use_photons = useTabs = useDvodeF90 = useTopology = useFlux = skipDup = False
useCoolingCEN = useCoolingH2 = useCoolingH2GP98 = useCoolingHD = useCoolingZ = use_cooling = useCoolingDust = useCoolingCompton = useH2opacity = useCoolingCIE = False
useCoolingZC = useCoolingZCp = useCoolingZSi = useCoolingZSip = useCoolingZO = useCoolingZOp = useCoolingZFe = useCoolingZFep = False
useReverse = useCustomCoe = useODEConstant = cleanBuild = usePlainIsotopes = useDust = use_thermo = False
usePhIoniz = useHeatingCompress = useHeatingPhoto = useHeatingChem = useDecoupled = useCoolingdH = useHeatingdH = False
pedanticMakefile = False
useX = has_plot = useFakeOpacity = doIndent = useTlimits = True
useDustGrowth = useDustSputter = useDustH2 = useDustT = False
typeGamma = "DEFAULT"
test_name = "default"
is_test = False
TlimitOpLow = "GE"
TlimitOpHigh = "LT"
customCoeFunction = "[CUSTOM COE FUNCTION NOT SET!]"
buildFolder = "build/"
TminAuto = 1e99
TmaxAuto = -1e99
RTOL = 1e-4 #default relative tolerance
ATOL = 1e-20 #default absolute tolerance
dustArraySize = dustTypesSize = 0
#select test name
for arg in sys.argv:
	if("test=" in arg):
		is_test = True
		test_name = (arg.strip().replace("-test=",""))
		print "Reading option -test (test="+test_name+")"
		if(test_name=="planet"):
			[sys.argv.append(x) for x in ["-useN","-reverse"]]
			filename = "networks/react_planet"
		elif(test_name=="CLOUD"):
			[sys.argv.append(x) for x in ["-useN","-iRHS"]]
			filename = "networks/react_WH2008"
		elif(test_name=="fake"):
			[sys.argv.append(x) for x in ["-forceRWORK=200"]]
			filename = "networks/react_fake"
		elif(test_name=="topology"):
			[sys.argv.append(x) for x in ["-useN","-iRHS","-useTopology"]]
			filename = "networks/react_WH2008"
		elif(test_name=="flux"):
			[sys.argv.append(x) for x in ["-useN","-iRHS","-useFlux"]]
			filename = "networks/react_WH2008"
		elif(test_name=="cooling"):
			[sys.argv.append(x) for x in ["-useN","-cooling=ATOMIC,H2,HD,Z,DH,H2GP98"]]
			filename = "networks/react_primordial"
		elif(test_name=="shock1Dcool"):
			[sys.argv.append(x) for x in ["-cooling=H2,HD,Z,DH"]]
			filename = "networks/react_primordial"
		elif(test_name=="shock1D"):
			filename = "networks/react_primordial"
		elif(test_name=="shock1Dphoto"):
			[sys.argv.append(x) for x in ["-usePhIoniz", "-heating=PHOTO","-cooling=ATOMIC,H2,HD,Z","-useEquilibrium"]]
			filename = "networks/react_primordial_photo"
		elif(test_name=="shock1Dlarge"):
			[sys.argv.append(x) for x in ["-iRHS"]]
			filename = "networks/react_WH2008"
		elif(test_name=="shock1Dbuff"):
			[sys.argv.append(x) for x in ["-usePhIoniz", "-heating=PHOTO","-cooling=ATOMIC,H2,HD,Z","-useEquilibrium"]]
			filename = "networks/react_primordial_photo"
		elif(test_name=="dust"):
			[sys.argv.append(x) for x in ["-dust=10,C,Si","-useN"]]
			filename = "networks/react_primordial"
		elif(test_name=="compact"):
			[sys.argv.append(x) for x in ["-compact"]]
			filename = "networks/react_primordial"
		elif(test_name=="map"):
			[sys.argv.append(x) for x in ["-cooling=ATOMIC,H2,HD", "-heating=PHOTO","-usePhIoniz"]]
			filename = "networks/react_primordial_photo"
		elif(test_name=="collapse"):
			[sys.argv.append(x) for x in ["-cooling=ATOMIC,H2,COMPTON,CIE", "-heating=COMPRESS,CHEM","-useH2opacity","-useN","-gamma=FULL"]]
			filename = "networks/react_primordial"
		elif(test_name=="collapseZ"):
			[sys.argv.append(x) for x in ["-cooling=ATOMIC,H2,COMPTON,CIE,CII,OI", "-heating=COMPRESS,CHEM","-useH2opacity","-useN","-gamma=FULL","-ATOL=1d-40"]]
			filename = "networks/react_primordialZ"
		elif(test_name=="collapseUV"):
			[sys.argv.append(x) for x in ["-cooling=ATOMIC,H2,COMPTON,CIE", "-heating=COMPRESS,CHEM","-useH2opacity","-useN","-gamma=FULL"]]
			filename = "networks/react_primordial_UV"
		elif(test_name=="collapseDUST"):
			[sys.argv.append(x) for x in ["-cooling=ATOMIC,H2,COMPTON,CIE,DUST", "-heating=COMPRESS,CHEM","-useH2opacity","-useN","-gamma=FULL","-dust=1,C","-dustOptions=TDUST"]]
			filename = "networks/react_primordial"
		else:
			print "ERROR: test \""+test_name+"\" not present!"
			sys.exit()
		break
#get filename
if(not(is_test)): filename = sys.argv[1]

#set implicit RHS
if("-iRHS" in sys.argv):
	use_implicit_RHS = True
	solver_MF = 222
	print "Reading option -iRHS"
#force MF=21
if("-forceMF=21" in sys.argv):
	solver_MF = 21
	print "Reading option -forceMF=21"
#force MF=222
if("-forceMF=222" in sys.argv):
	solver_MF = 222
	print "Reading option -forceMF=222"
#use numeric density instead of fractions as input
if("-useN" in sys.argv):
	useX = False
	print "Reading option -useN"
#force to use photons
if("-usePhot" in sys.argv):
	use_photons = True
	print "Reading option -usePhot"
#use rate tables
if("-useTabs" in sys.argv):
	useTabs = True
	print "Reading option -useTabs"
#use f90 solver
if("-useDvodeF90" in sys.argv):
	useDvodeF90 = True
	print "Reading option -useDvodeF90"
#use topology reduction
if("-useTopology" in sys.argv):
	useTopology = True
	print "Reading option -useTopology"
#use topology reduction
if("-useFlux" in sys.argv):
	useFlux = True
	print "Reading option -useFlux"
#do report
if("-report" in sys.argv):
	doReport = True
	print "Reading option -report"
#check mass conservation
if("-checkConserv" in sys.argv):
	checkConserv = True
	print "Reading option -checkConserv"
#use reaction indexes in reaction file
if("-useFileIdx" in sys.argv):
	useFileIdx = True
	print "Reading option -useFileIdx"
#write a single compact file krome_all.f90
if("-compact" in sys.argv):
	buildCompact = True
	print "Reading option -compact"
#perform a clean build
if("-clean" in sys.argv):
	cleanBuild = True
	print "Reading option -clean"
#build isotopes automatically
if("-usePlainIsotopes" in sys.argv):
	usePlainIsotopes = True
	print "Reading option -usePlainIsotopes"
#use photoionization from Verner et al. 1996
if("-usePhIoniz" in sys.argv):
	usePhIoniz = True
	print "Reading option -usePhIoniz"
#use equilibrium check to break loops earlier
if("-useEquilibrium" in sys.argv):
	useEquilibrium = True
	print "Reading option -useEquilibrium"
#do not use temperature limits
if("-noTlimits" in sys.argv):
	useTlimits = False
	print "Reading option -noTlimits"
#skip duplicated reactions
if("-skipDup" in sys.argv):
	skipDup = True
	print "Reading option -skipDup"
#skip duplicated reactions
if("-pedantic" in sys.argv):
	pedanticMakefile = True
	print "Reading option -pedantic"
#use reverse kinetics
if("-reverse" in sys.argv):
	useReverse = True
	print "Reading option -reverse"
#use H2opacity following 
if("-useH2opacity" in sys.argv):
	useH2opacity = True
	print "Reading option -useH2opacity"

#determine Tgas limit operators
for arg in sys.argv:
	if("Tlimit=" in arg):
		myTlimit = (arg.strip().replace("-Tlimit=",""))
		myTlimit = myTlimit.replace("[","").replace("]","").split(",")
		TlimitOpHigh = myTlimit[1].strip().upper()
		TlimitOpLow = myTlimit[0].strip().upper()
		allOps = ["LE","LT","GE","GT"]
		if(not(TlimitOpLow in allOps) or not(TlimitOpHigh in allOps)):
			die("ERROR: on -Tlimit operators must be one of the followings: "+(", ".join(allOps)))
		print "Reading option -Tlimit (Low="+TlimitOpLow+", High="+TlimitOpHigh+")"
		break
#determine cooling types
for arg in sys.argv:
	if("cooling=" in arg):
		myCools = arg.strip().replace("-cooling=","").split(",")
		allCools = ["ATOMIC","H2","HD","Z","DH","DUST","H2GP98","COMPTON","CIE","CI","CII","SiI","SiII","OI","OII","FeI","FeII"]
		for coo in myCools:
			if(not(coo in allCools)):
				die("ERROR: Cooling \""+coo+"\" is unknown!\nAvailable coolings are: "+(", ".join(allCools)))

		if("ATOMIC" in myCools): useCoolingCEN = True
		if("H2" in myCools): useCoolingH2 = True
		if("H2GP98" in myCools): useCoolingH2GP98 = True
		if("HD" in myCools): useCoolingHD = True
		if("DH" in myCools): useCoolingdH = True
		if("DUST" in myCools): useCoolingDust = True
		if("COMPTON" in myCools): useCoolingCompton = True
		if("CIE" in myCools): useCoolingCIE = True
		if("Z" in myCools): useCoolingZ = useCoolingZC = useCoolingZCp = useCoolingZSi = useCoolingZSip = useCoolingZO = useCoolingZOp = useCoolingZFe = useCoolingZFep = True
		if("CI" in myCools): useCoolingZ = useCoolingZC = True
		if("CII" in myCools): useCoolingZ = useCoolingZCp = True
		if("SiI" in myCools): useCoolingZ = useCoolingZSi = True
		if("SiII" in myCools): useCoolingZ = useCoolingZSip = True
		if("OI" in myCools): useCoolingZ = useCoolingZO = True
		if("OII" in myCools): useCoolingZ = useCoolingZOp = True
		if("FeI" in myCools): useCoolingZ = useCoolingZFe = True
		if("FeII" in myCools): useCoolingZ = useCoolingZFep = True
					
		use_cooling = True
		
		hasDust = False
		for aa in sys.argv:
			if("dust=" in aa): hasDust = True
		if(useCoolingDust and not(hasDust)):
			die("ERROR: to include dust cooling you need dust (use -dust=[see help]).")

		use_thermo = True

		print "Reading option -cooling ("+(",".join(myCools))+")"
		
#determine heating types
for arg in sys.argv:
	if("heating=" in arg):
		myHeat = arg.strip().replace("-heating=","").upper().split(",")
		allHeats = ["COMPRESS","PHOTO","CHEM","DH"]
		for hea in myHeat:
			if(not(hea in allHeats)):
				die("ERROR: Heating \""+hea+"\" is unknown!\nAvailable heatings are: "+(", ".join(allHeats)))

		if("COMPRESS" in myHeat): useHeatingCompress = True
		if("PHOTO" in myHeat): useHeatingPhoto = True
		if("CHEM" in myHeat): useHeatingChem = True
		if("DH" in myHeat): useHeatingdH = True

		use_thermo = True
		if(not(usePhIoniz) and useHeatingPhoto):
			die("ERROR: if you use photoheating you have to include potoionization via -usePhIoniz")

		print "Reading option -heating ("+(",".join(myHeat))+")"
	

#force rwork size
for arg in sys.argv:
	if("testFile=" in arg):
		myrwork = (arg.strip().replace("-testFile=",""))
		is_test = True
		test_name = myrwork
		print "Reading option -testFile (file="+str(myrwork)+")"
		break

#force rwork size
for arg in sys.argv:
	if("forceRWORK=" in arg):
		myrwork = (arg.strip().replace("-forceRWORK=",""))
		force_rwork = True
		print "Reading option -forceRWORK (RWORK="+str(myrwork)+")"
		break
#use custom function for coefficient instead of coe_tab()
for arg in sys.argv:
	if("useCustomCoe=" in arg):
		customCoeFunction = (arg.strip().replace("-useCustomCoe=",""))
		useCustomCoe = True
		print "Reading option -useCustomCoe (Expression="+str(customCoeFunction)+")"
		break
#use function to append after each ODE
for arg in sys.argv:
	if("useODEConstant=" in arg):
		ODEConstant = (arg.strip().replace("-useODEConstant=",""))
		useODEConstant = True
		print "Reading option -useODEConstant (Constant="+str(ODEConstant)+")"
		break
#dust
hasDustOptions = False
for arg in sys.argv:
	if("dustOptions=" in arg): hasDustOptions = True
for arg in sys.argv:
	if("dust=" in arg):
		dustopt = (arg.strip().replace("-dust=",""))
		adust = dustopt.split(",")
		useDust = True
		if(len(adust)<2): die("ERROR: you must specify dust size and type(s), e.g. -dust=20,C,Si")
		if(use_implicit_RHS): die("ERROR: you cannot use dust AND implicit RHS: remove -iRHS option")
		dustArraySize = int(adust[0])
		dustTypes = adust[1:]
		dustTypesSize = len(dustTypes)
		print "Reading option -dust (size="+str(dustArraySize)+", type(s)="+(",".join(dustTypes))+")"
		if(not(hasDustOptions)):
			print "ERROR: -dust flag needs to define -dustOptions=[see help])"
			sys.exit()
		break
#dust options
for arg in sys.argv:
	if("dustOptions=" in arg):
		if(not(useDust)): die("ERROR: you need -dust=[see help] to activate dust options!")
		dustopt = (arg.strip().replace("-dustOptions=",""))
		dustOptions = dustopt.split(",")
		if("GROWTH" in dustOptions): useDustGrowth = True
		if("SPUTTER" in dustOptions): useDustSputter = True
		if("H2" in dustOptions): useDustH2 = True
		if("TDUST" in dustOptions): useDustT = True
		print "Reading option -dustOptions (options="+(",".join(dustOptions))+")"
		break

#project name folder
for arg in sys.argv:
	if("project=" in arg):
		projectName = (arg.strip().replace("-project=",""))
		print "Reading option -project (name="+str(projectName)+")"
		buildFolder = "build_"+projectName+"/"
		fout = open(projectName+".kpj","w")
		fout.write((" ".join(sys.argv)))
		fout.close()
		break
#typeGamma
for arg in sys.argv:
	if("gamma=" in arg):
		typeGamma = (arg.strip().replace("-gamma=",""))
		typeGamma = typeGamma.replace("\"","")
		print "Reading option -gamma (gamma="+str(typeGamma)+")"
		break

#ATOL
for arg in sys.argv:
	if("ATOL=" in arg):
		ATOL = (arg.strip().replace("-ATOL=",""))
		print "Reading option -ATOL (ATOL="+str(ATOL)+")"
		break

#RTOL
for arg in sys.argv:
	if("RTOL=" in arg):
		RTOL = (arg.strip().replace("-RTOL=",""))
		print "Reading option -RTOL (RTOL="+str(RTOL)+")"
		break

#show help
if("-help" in sys.argv or "-h" in sys.argv or "--help" in sys.argv):
	get_usage()


print

use_RHS_variable = False

separator = "," #separator character
krome = "" #krome global variable prefix

#chech if reactions file exists
if(not(os.path.isfile(filename))): die("ERROR: Reaction file \""+filename+"\" doesn't exist!")


solver_moss = int(solver_MF/100)
solver_meth = int(solver_MF/10) % 10
solver_miter = solver_MF % 10

print "solver info:"
print " MF:",solver_MF
print " MOSS+METH+MITER:","+".join([str(x) for x in [solver_moss,solver_meth,solver_miter]])
print

me =  9.10938188e-28 #electron mass (g)
mp = 1.67262158e-24 #proton mass (g)
mn = 1.6725e-24 #neutron mass (g)
menp = me + mp + mn
#mass dictionary
mass_dic = {'H':me+mp,
	'D':menp,
	'He':2.*(menp),
	'Li':3.*(me+mp)+4.*mn,
	'Be':4.*(me+mp)+5.*mn,
	'C':6.*(menp),
	'N':7.*(menp),
	'O':8.*(menp),
	'F':9.*(menp)+mn,
	'Mg':12.*(menp),
	'Na':(me+mp)*11+mn*12,
	'Si':14.*(menp),
	'P':15.*(menp)+mn,
	'S':(menp)*16,
	'Cl':(menp)*17+mn,
	'Fe':(me+mp)*26+mn*29,
	'GRAIN0': 100*6*(menp),
	'GRAIN-': 100*6*(menp)+me,
	'GRAIN+': 100*6*(menp)-me,
	'PAH': 30*6*(menp),
	'PAH-': 30*6*(menp)+me,
	'PAH+': 30*6*(menp)-me,
	'O(1D)':8.*(menp),
	'O(3P)':8.*(menp),
	'CR':0.,
	'M':0.,
	'g':0.,
	'E':me,
	'-':me,
	'+':-me}

#fake species FK1,FK2,...
for i in range(10):
	mass_dic['FK'+str(i)] = 1.

#exited levels of some molecules
for i in range(9):
	mass_dic['CH2_'+str(i+1)] = 6.*(menp) + 2.*(me+mp)
	mass_dic['SO2_'+str(i+1)] = 16.*(menp) + 2.*8.*(menp)

#build isotopes (including some non-esistent) as [n]A
#with -usePlainIsotopes build as nA
atoms_iso = ["H","He","Li","Be","B","C","N","O","F","Ne","Na","Mg","Al","Si","P","S","Cl","Ar","K","Ca","Fe","Co","Ni"]
atoms_p = [i+1 for i in range(20)] + [26,27,28]
if(len(atoms_iso)!=len(atoms_p)): die("ERROR: in building isotopes the length of the atoms array and the number of protons array mismatch!")
for aiso in atoms_iso:
	protons = atoms_p[atoms_iso.index(aiso)] #get proton numbers
	for i in range(protons,80):
		iso_name = "["+str(i)+aiso+"]"
		if(usePlainIsotopes): iso_name = str(i)+aiso
		mass_dic[iso_name] = protons*(me+mp) + ((i-protons)*mn)

##################################
##################################
##################################

mass_dic = dict([[k.upper(),v] for (k,v) in mass_dic.iteritems()])
atoms = sorted(mass_dic, key = lambda x: len(x),reverse=True)

print "Reading from file \""+filename+"\"..."
spec_names = [] #string
specs = []
reacts = []
idx_list = [] #store reaction index in case of -useFileIdx
pseudo_hash_list = []
fh = open(filename,"rb")
rcount = 0 #count reactions
found_one = False #flag to control if at least one reaction has been found
unmatch_idx = False #controls if the reaction index in the file match the sequential index
#default position in input array line
iidx = 0 #position of the index
skipped_dupl = 0 #number of duplicated reaction skipped
ireact = range(1,4) #positions of the reactants
iprod = range(4,8) #position of the products
iTmin = 8 #position of tmin
iTmax = 9 #position of tmax
irate = 10 #position of the rate in F90 style
hasFormat = False
format_items = 4+len(ireact)+len(iprod)
if(skipDup): fdup = open("duplicates.log","w")
for row in fh:
	srow = row.strip() #stripped row
	if(srow.strip()==""): continue #looks for blank line
	if(srow[0]=="#"): continue #looks for comment line
	#search for format string
	if("@format:" in srow):
		hasFormat = True
		srow = srow.replace("@format:","") #remove 
		print "Using custom format:"
		print srow
		arow = srow.split(",") #split format line
		if(len(arow)<6):
			print "ERROR: format line must contains at least 6 elements"
			print " idx,R,P,Tmin,Tmax,rate"
			print " You provided "+str(len(arow))+" elements:"
			print " "+srow
			sys.exit()
		ipos = 0 #count items in the splitted line
		ireact = [] #reactants index array
		iprod = [] #products index array
		idxFound = tminFound = tmaxFound = rateFound = False
		format_items = len(arow)
		for x in arow:
			x = x.lower().strip() #lower trimmed item
			if(x=="idx"): 
				iidx = ipos #index position
				idxFound = True
			if(x=="r"): ireact.append(ipos) #reactants positions
			if(x=="p"): iprod.append(ipos) #products positions
			if(x=="tmin"): 
				iTmin = ipos #min temperature position
				tminFound = True
			if(x=="tmax"): 
				iTmax = ipos #max temperature position
				tmaxFound = True
			if(x=="rate" or x=="k"): 
				irate = ipos #rate in F90 style position
				rateFound = True
			ipos += 1 #increase position
		if(not(tminFound) or not(tmaxFound) or not(rateFound)):
			print "ERROR: format must contain tmin, tmax, and rate"
			sys.exit()
		continue #skip format line (it is not a reaction line)
	arow = srow.split(separator,format_items-1) #split only N+1 elements with N seprations
	if(len(arow)!=format_items): 
		print "WARNING: wrong format for reaction "+str(rcount+1)
		print srow
		a = raw_input("Any key to continue q to quit... ")
		if(a=="q"): print sys.exit()
		continue #check line format (N elements, 4=idx+Tmin+Tmax+rate)
	found_one = True
	rcount += 1
	myrea = reaction() #create object reaction

	if(useFileIdx):
		if(not(hasFormat) or (hasFormat and idxFound)):
			reaction_idx = int(arow[0]) #index of the reaction (from file)
			if(reaction_idx<1): die("ERROR: reaction index must be > 0!\n Check your reaction file!")
			if(reaction_idx in idx_list):
				die("ERROR: reaction index "+str(reaction_idx)+" already present!\n Check your reaction file!")
			myrea.idx = reaction_idx
			rcount = reaction_idx
	else:
		myrea.idx = rcount
		if(not(hasFormat) or (hasFormat and idxFound)):
			if(rcount!=int(arow[0])): unmatch_idx = True

	reactants = [arow[x] for x in ireact]
	products = [arow[x] for x in iprod]

	opTlist = ["<",">",".LE.",".GE.",".LT.",".GT."]
	myrea.TminOp = TlimitOpLow
	myrea.TmaxOp = TlimitOpHigh
	for op in opTlist:
		if(op in arow[iTmin]):
			arow[iTmin] = arow[iTmin].replace(op,"")
			myrea.TminOp = op.replace(">","GT").replace("<","LT").replace(".","")
			break
	for op in opTlist:
		if(op in arow[iTmax]):
			arow[iTmax] = arow[iTmax].replace(op,"")		
			myrea.TmaxOp = op.replace(">","GT").replace("<","LT").replace(".","")
			break


	myrea.Tmin = format_double(arow[iTmin]) #get Tmin
	myrea.Tmax = format_double(arow[iTmax]) #get Tmax
	TminAuto = min(float(arow[iTmin].lower().replace("d","e")), TminAuto)
	TmaxAuto = max(float(arow[iTmax].lower().replace("d","e")), TmaxAuto)

	myrea.krate = arow[irate] #get reaction rate written in F90 style
	if(useCustomCoe): myrea.krate = "0.d0" #when custom function is used standard coefficient are set to zero
	#loop over reactants to grep molecules
	for r in reactants:
		if(r.strip()=="g" and not(use_photons)): continue
		if(r.strip()!=""):
			mol = parser(r,mass_dic,atoms)
			if(not(mol.name in spec_names)):
				spec_names.append(mol.name)
				specs.append(mol)
			mol.idx = spec_names.index(mol.name) + 1
			myrea.reactants.append(mol) #add molecule object to reactants
	#loop over prodcuts to grep molecules
	for p in products:
		if(p.strip()=="g" and not(use_photons)): continue
		if(p.strip()!=""):
			mol = parser(p,mass_dic,atoms)
			if(not(mol.name in spec_names)):
				spec_names.append(mol.name)
				specs.append(mol)
			mol.idx = spec_names.index(mol.name) + 1
			myrea.products.append(mol) #add molecule object to products

	myrea.build_verbatim() #build reaction as string (e.g. A+B->C)
	myrea.reactants = sorted(myrea.reactants, key=lambda r:r.idx) #sort reactants
	myrea.products = sorted(myrea.products, key=lambda p:p.idx) #sort products
	myrea.build_RHS() #build RHS in F90 format (e.g. k(2)*n(10)*n(8) )
	myrea.build_phrate() #build photoionization rate
	myrea.check() #check mass and charge conservation
	if(myrea.krate.count("(")!=myrea.krate.count(")")):
		print "ERROR: unbalanced brakets in reaction "+str(myrea.idx)
		print " "+myrea.verbatim
		print " rate = "+myrea.krate
		sys.exit()

	skip_append = False
	if(skipDup):
		myrea.build_pseudo_hash() #build pseudo_hash
		if(myrea.pseudo_hash in pseudo_hash_list): 
			skip_append = True
			skipped_dupl += 1
			fdup.write(str(myrea.idx)+" "+myrea.verbatim+"\n")
			rcount -= 1
		else:
			pseudo_hash_list.append(myrea.pseudo_hash)
	if(not(skip_append)): reacts.append(myrea)

if(skipDup): fdup.close()

#check file format
if(not(found_one)):
	die("ERROR: no valid reactions found in file \""+filename+"\"")
if(unmatch_idx):
	print "WARNING: index in \""+filename+"\" are not sequential!"

print "done!"


#do reverse reaction if needed
if(useReverse):
	print
	print "reversing reactions..."
	count_reverse = len(reacts)
	reacts_copy = [x for x in reacts] #create a copy of reacts to loop on
	#loop over found reactants
	for myrea in reacts_copy:
		#skip reactions with more than four products
		if(len(myrea.products)>3):
			print "WARNING: in reversing reaction "+myrea.verbatim+" more than 3 products found! Skipped."
			continue
		else:
			count_reverse += 1
			myrev = reaction() #create object reaction for reverse
			myrev.idx = count_reverse
			myrev.Tmin = myrea.Tmin #get Tmin
			myrev.Tmax = myrea.Tmax #get Tmax
			myrev.reactants = myrea.products
			myrev.products = myrea.reactants
			myrev.TminOp = myrea.TminOp #get Tmin operator
			myrev.TmaxOp = myrea.TmaxOp #get Tmax operator
			myrev.build_verbatim() #build reaction as string (e.g. A+B->C)
			myrev.verbatim += " (REV)" #append REV label to reaction string
			myreactants = myrev.reactants #get list of reactants
			myproducts = myrev.products #get list of products
			myrev.krate = myrea.krate #set the forward reaction
			myrev.krate = myrev.doReverse() #compute reverse reaction using Simoncini2013PRL
			myrev.build_RHS() #build RHS in F90 format (e.g. k(2)*n(10)*n(8) )
			myrev.check() #check mass and charge conservation
			reacts.append(myrev)
	print "Inverse reaction added: "+str(count_reverse)


if(skipDup): print "Skipped duplicated reactions:",skipped_dupl


#add all the metals to cooling
if(useCoolingZ):
	Zcools = ["C","C+","Si","Si+","O","O+","Fe","Fe+"]
	for zcool in Zcools:
		zFound = False #flag metal found
		#loop on specs to found metals
		for mol in specs:
			#when found break loop
			if(mol.name.lower()==zcool.lower()):
				zFound = True
				break
		#if not found parse and add
		if(not(zFound)):
			print "Add species \""+zcool+"\" (request by metal cooling)"
			mymol = parser(zcool,mass_dic,atoms)
			mymol.idx = len(specs)+1
			specs.append(mymol)

#add minimum value to rates and computes reaction enthalpy
for rea in reacts:
	if(not("krome_" in rea.krate)): rea.krate = "1d-40 + ("+rea.krate+")"

if(useCoolingdH or useHeatingdH):
	for i in range(len(reacts)):
		reacts[i].enthalpy()
		vrb = reacts[i].verbatim.strip()
		avrb = vrb.split("->")
		print avrb[0]+" "*(15-len(avrb[0])),"->",avrb[1]+" "*(15-len(avrb[1])),reacts[i].dH,"erg"

#add dust to problem
if(useDust):
	print
	#look for dust atoms in species found
	for dType in dustTypes:
		dTypeFound = False #flag atom found
		#loop on specs to found dust atom
		for mol in specs:
			#when found break loop
			if(mol.name.lower()==dType.lower()):
				dTypeFound = True
				break
		#if not found add to specs parsing the name (e.g. Si)
		if(not(dTypeFound)):
				print "Add species \""+dType+"\" (request by dust type)"
				mymol = parser(dType,mass_dic,atoms)
				mymol.idx = len(specs)+1
				specs.append(mymol)
	#add dust bins as species
	for dType in dustTypes:
		for i in range(dustArraySize):
				#create the object named dust_type_index
				mymol = molec()
				mymol.name = "dust_"+dType+"_"+str(i)
				mymol.charge = 0
				mymol.mass = 0.e0
				mymol.ename = "dust_"+dType+"_"+str(i)
				mymol.fidx = "idx_dust_"+dType+"_"+str(i)
				mymol.idx = len(specs)+1
				specs.append(mymol)

	print "Dust added:",dustArraySize*dustTypesSize

#look for photons and CR
has_g = has_CR = False

for mol in specs:
	if(mol.name=="g"):
		has_g = True
	if(mol.name=="CR"):
		has_CR = True

#append CR as species named CR
if(not(has_CR)):
	mymol = molec()
	mymol.name = "CR"
	mymol.charge = 0
	mymol.mass = 0.e0
	mymol.ename = "CR"
	mymol.fidx = "idx_CR"
	mymol.idx = len(specs)+1
	specs.append(mymol)
	photon_species = mymol #store object
	print "Cosmic Rays (CR) added!"

#append photons as species named g
if(not(has_g)):
	mymol = molec()
	mymol.name = "g"
	mymol.charge = 0
	mymol.mass = 0.e0
	mymol.ename = "g"
	mymol.fidx = "idx_g"
	mymol.idx = len(specs)+1
	specs.append(mymol)
	photon_species = mymol #store object
	print "Photons (g) added!"

#append temperature as species named Tgas
mymol = molec()
mymol.name = "Tgas"
mymol.charge = 0
mymol.mass = 0.e0
mymol.ename = "Tgas"
mymol.fidx = "idx_Tgas"
mymol.idx = len(specs)+1
specs.append(mymol)
Tgas_species = mymol #store object

#append dummy as species named dummy
mymol = molec()
mymol.name = "dummy"
mymol.charge = 0
mymol.mass = 0.e0
mymol.ename = "dummy"
mymol.fidx = "idx_dummy"
mymol.idx = len(specs)+1
specs.append(mymol)
dummy = mymol #store object

#print found values
print
print "ODEs needed:", len(specs)
print "Reactions found:", len(reacts)
print "Species found:", len(specs)-4-dustArraySize*dustTypesSize

#dump species to log file
fout = open("species.log","w")
idx = 0
for mol in specs:
	idx += 1
	fout.write(str(idx)+"\t"+mol.name+"\t"+mol.fidx+"\n")
fout.close()

#dump reactions to log file
fout = open("reactions.log","w")
idx = 0
for rea in reacts:
	idx += 1
	fout.write(str(rea.idx)+"\t"+rea.verbatim+"\n")
fout.close()

print
#include dust in ODE array partition
sdust = ""
if(useDust):
	#include dust by types
	for dType in dustTypes:
		sdust += " + ["+str(dustArraySize)+" "+dType+"-dust]"
sODEpart = "ODE partition: [" + str(len(specs)-4-dustArraySize*dustTypesSize) + " atom/mols] "+sdust+" + [1 CR] + [1 PHOT] + [1 Tgas] + [1 dummy] = "+str(len(specs))+" ODEs"
print sODEpart
#if species are few print list of species
if(len(specs)<20): print "ODEs list: "+(", ".join([x.name for x in specs]))
print "Species list in species.log"
print

print "Temperature range found min/max (K):", TminAuto, "/",TmaxAuto

#create explicit differentials
dns = ["dn("+str(sp.idx)+") = 0.d0" for sp in specs] #initialize
for rea in reacts:
	for r in rea.reactants:
		dns[r.idx-1] = dns[r.idx-1].replace(" = 0.d0"," =")
		dns[r.idx-1] += " -"+rea.RHS
	for p in rea.products:
		dns[p.idx-1] = dns[p.idx-1].replace(" = 0.d0"," =")
		dns[p.idx-1] += " +"+rea.RHS

#add dust to ODEs
nmols = len(specs)-4-dustArraySize*dustTypesSize
if(useDust):
	j = 0
	for dType in dustTypes:
		for i in range(dustArraySize):
			j += 1
			#******growth / sputtering******
			if(useDustGrowth):
				dns[nmols+j-1] += " + krome_dust_grow(n("+str(nmols+j)+"),n(idx_"+dType+"),Tgas"
				dns[nmols+j-1] += ",krome_dust_T("+str(j)+"),vgas,krome_dust_asize("+str(j)+"))"
			if(useDustSputter):
				dns[nmols+j-1] += " - krome_dust_sput_DS79(Tgas,krome_dust_asize("+str(j)+"),ntot,n("+str(nmols+j)+"))"

#find the maximum number of products and reactants
maxnprod = maxnreag = 0
for rea in reacts:
	maxnprod = max(maxnprod, len(rea.products))
	maxnreag = max(maxnreag, len(rea.reactants))

print "Max number of reactants:", maxnreag
print "Max number of products:", maxnprod

#create implicit RHS arrays
arr_rr = [[] for i in range(maxnreag)]
arr_pp = [[] for i in range(maxnprod)]
for rea in reacts:
	for i in range(maxnreag):
		if(i<len(rea.reactants)): arr_rr[i].append(rea.reactants[i].idx)
		else: arr_rr[i].append(dummy.idx)
	for i in range(maxnprod):
		if(i<len(rea.products)): arr_pp[i].append(rea.products[i].idx)
		else: arr_pp[i].append(dummy.idx)
implicit_arrays = ""
for i in range(len(arr_rr)):
	implicit_arrays += "arr_r"+str(i+1)+"(:) = (/"+(",".join([str(x) for x in arr_rr[i]]))+"/)\n"
for i in range(len(arr_pp)):
	implicit_arrays += "arr_p"+str(i+1)+"(:) = (/"+(",".join([str(x) for x in arr_pp[i]]))+"/)\n"

#wrap RHS (e.g. knn+knn=2*knn)
dnw = []
for dn in dns:
	RHSs = []
	RHSc = []
	dnspl =  dn.strip().split()
	dns = " ".join(dnspl[:2])
	for p in dnspl[2:]:
		if(not(p in RHSs)):
			RHSs.append(p)
			RHSc.append(0)
		RHSc[RHSs.index(p)] += 1
	for i in range(len(RHSs)):
		if((i+1) % 4 == 0): dns += "&\n" #break long lines
		if("-" in RHSs[i] and RHSc[i]>1): dns += RHSs[i].replace("-"," -"+str(RHSc[i])+".d0*")
		if("+" in RHSs[i] and RHSc[i]>1): dns += RHSs[i].replace("+"," +"+str(RHSc[i])+".d0*")
		if(RHSc[i]==1): dns+= " "+RHSs[i]
	dnw.append(dns)

#create explicit JAC
neq = len(specs)
jac = [["pdj("+str(j+1)+") = 0.d0" for i in range(neq)] for j in range(neq)]
jsparse = [[0 for i in range(neq)] for j in range(neq)]
for rea in reacts:
	for ri in range(len(rea.reactants)):
		r1 = rea.reactants[ri]
		sjac = "k("+str(rea.idx)+")"
		for rj in range(len(rea.reactants)):
			r2 = rea.reactants[rj]
			if(ri!=rj):
				sjac += "*n("+str(r2.idx)+")"
		for rr in rea.reactants:
			jac[rr.idx-1][r1.idx-1] = jac[rr.idx-1][r1.idx-1].replace(" = 0.d0"," =")
			jac[rr.idx-1][r1.idx-1] += " -"+sjac
			jsparse[rr.idx-1][r1.idx-1] = 1
		for pp in rea.products:
			jac[pp.idx-1][r1.idx-1] = jac[pp.idx-1][r1.idx-1].replace(" = 0.d0"," =")
			jac[pp.idx-1][r1.idx-1] += " +"+sjac
			jsparse[pp.idx-1][r1.idx-1] = 1

for i in range(neq):
	if(not(use_thermo)): break
	jsparse[i][Tgas_species.idx-1] = jsparse[Tgas_species.idx-1][i] = 1
	s = str(i+1)
	if(specs[i].name!="dummy" and specs[i].name!="CR" and specs[i].name!="g"):
		jac[Tgas_species.idx-1][i] = "if(abs(n("+s+") - jac_nold("+s+"))>1d-10) pdj(idx_Tgas) = (jac_dn(idx_Tgas) - jac_dnold(idx_Tgas)) / (n("+s+") - jac_nold("+s+"))"

#create IAC/JAC (see DLSODES manual)
isum = 1
ia = [1]
ja = []
for i in range(neq):
	isum += sum(jsparse[i])
	ia.append(isum)
	for j in range(neq):
		if(jsparse[i][j]==1): ja.append(j+1)
nnz = len(ja)
iaf = "IWORK(31:" + str(30+neq+1) + ") = (/" + (",".join([str(x) for x in ia])) + "/)"
jaf = "IWORK("+str(31+neq+1)+":"+str(31+neq+nnz)+") = (/"+(",".join([str(x) for x in ja]))+"/)"
pnnz = round(nnz*100./neq/neq,2)
print
print "Jacobian non-zero elements:",nnz,"over",neq*neq
print "("+str(pnnz)+"% of total elements, sparsity = "+str(100.-pnnz)+"%)"

#if MF=222 no need for sparsity structure arrays
if(solver_MF == 222):
	iaf = jaf = ""

#estimate size of RWORK array (see DLSODES manual)
neq = len(specs) #number of equations
nrea = len(reacts) #number of reactions
lenrat = 2
nnz_estimate = pow(neq,2) - nrea #estimate non-zero elements (inaccurate)
nnz = max(nnz, nnz_estimate) #estimate can be more realistic than nnz calculation
if(nnz<0):
	die("ERROR: nnz<0, please check RWORK size estimation!")

#calculate LWM
if(solver_miter==0):
	lwm = 0
elif(solver_miter==1):
	lwm = 2*nnz + 2*neq + (nnz+9*neq)/lenrat
elif(solver_miter==2):
	lwm = 2*nnz + 2*neq + (nnz+10*neq)/lenrat
elif(solver_miter==3):
	lwm = neq + 2
else:
	die("ERROR: solver_miter value "+str(solver_miter)+" unknown!")

#calculate LRW as in DLSODES documentation
if(solver_MF==10):
	lrw = 20+16*neq
elif(solver_MF in [11,111,211,12,112,212]):
	lrw = 20+16*neq+lwm
elif(solver_MF==13):
	lrw = 20+17*neq
elif(solver_MF==20):
	lrw = 20+9*neq
elif(solver_MF in [21,121,221,22,122,222]):
	lrw = 20+9*neq+lwm
elif(solver_MF==23):
	lrw = 22+10*neq
else:
	die("ERROR: solver_MF value "+str(solver_MF)+" unknown in LRW calculation!")

if(force_rwork):
	lrw = myrwork
#lrw = int(20+(2+0.5)*nnz + (11+4.5)*neq) #RWORK size

print "LWM:",lwm,"LRW:",lrw


#create build folder if not exists
if(not(os.path.exists(buildFolder))):
	os.mkdir(buildFolder)
	print "Created "+buildFolder
#remove everything
if(cleanBuild):
	clear_dir(buildFolder) #clear the build directory
	print "Deleted all contents in "+buildFolder
#remove only selected krome files
else:
	underFiles = ["commons","constants","cooling","dust","ode","reduction","subs","tabs","user",]
	delFiles = [buildFolder+"krome_"+x+".f90" for x in underFiles] + [buildFolder+x for x in ["krome.f90","opkda1.f","opkda2.f"]]
	delFiles += glob.glob(buildFolder+"*~") + glob.glob(buildFolder+"*.mod")
	delFiles += glob.glob(buildFolder+"*_genmod.f90") + glob.glob(buildFolder+"*.i90")
	#for dfile in delFiles:
		#print "deleting "+dfile


print
print "Prepearing files in /build..."

#build all the modules in a single file krome_all.f90
if(buildCompact):
	fout = open(buildFolder+"krome_all.f90","w")

#*********COMMONS****************
#write parameters in krome_commons.f90
print "- writing krome_commons.f90...",
fh = open("src/krome_commons.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_commons.f90","w")

#photoionization variables and functions
phvars = []
pheatvars = []
if(usePhIoniz):
	for react in reacts:
		if("krome_kph_" in react.krate):
			phvars.append(react.krate)
			pheatvars.append(react.krate.replace("krome_kph_","krome_pheat_"))

optVariables = ""
if(useDust):
	for dType in dustTypes:
		optVariables += "real*8,allocatable::dust_opt_asize_"+dType+"(:), dust_opt_nu_"+dType+"(:),dust_opt_Qabs_"+dType+"(:,:)\n"
		optVariables += "real*8,allocatable::dust_opt_Em_"+dType+"(:,:),dust_opt_Tbb_"+dType+"(:)\n"

skip = False
for row in fh:

	if(row.strip() == "#KROME_species_index"):
		for x in specs:
			fout.write("\tinteger,parameter::" + x.fidx + "=" + str(x.idx) + "\n")
	elif(row.strip() == "#KROME_parameters"):
			fout.write("\tinteger,parameter::nrea=" + str(len(reacts)) + "\n")
			fout.write("\tinteger,parameter::nmols=" + str(len(specs)-4-dustArraySize*dustTypesSize) + "\n")
			fout.write("\tinteger,parameter::nspec=" + str(len(specs)) + "\n")
			fout.write("\tinteger,parameter::ndust=" + str(dustArraySize*dustTypesSize) + "\n")
			fout.write("\tinteger,parameter::ndustTypes=" + str(dustTypesSize) + "\n")
	elif(row.strip() == "#KROME_header"):
		fout.write(get_licence_header())
	elif(row.strip() == "#KROME_implicit_arr_r"):
		for j in range(maxnreag):
			fout.write("integer::arr_r"+str(j+1)+"(nrea)\n")
	elif(row.strip() == "#KROME_implicit_arr_p"):
		for j in range(maxnprod):
			fout.write("integer::arr_p"+str(j+1)+"(nrea)\n")
	elif(row.strip() == "#KROME_photo_variables" and usePhIoniz and len(phvars)>0):
		fout.write("real*8::"+(",".join(phvars))+"\n")
	elif(row.strip() == "#KROME_photoheating_variables" and useHeatingPhoto):
		fout.write("real*8::"+(",".join(pheatvars))+"\n")
	elif(row.strip() == "#KROME_opt_variables"):
		fout.write(optVariables)
	else:
		if(row[0]!="#"): fout.write(row)

if(not(buildCompact)):
	fout.close()
print "done!"

#********* CONSTANTS ****************
fh = open("src/krome_constants.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_constants.f90","w")
for row in fh:
	if(row[0]!="#"): fout.write(row)
if(not(buildCompact)):
	fout.close()

#*********USER COMMONS****************
#write parameters in krome_user_commons.f90
if(not(file_exists(buildFolder+"krome_user_commons.f90"))):
	print "- writing krome_user_commons.f90...",

	fh = open("src/krome_user_commons.f90")
	fouta = open(buildFolder+"krome_user_commons.f90","w")

	for row in fh:
		row = row.replace("#KROME_header", get_licence_header())

		if(row[0]!="#"): fouta.write(row)

	fouta.close()
	print "done!"
else:
	print "WARNING: krome_user_commons.f90 not replaced!"
#*********SUBS****************
#write parameters in krome_subs.f90
print "- writing krome_subs.f90...",
fh = open("src/krome_subs.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_subs.f90","w")

sclist = []
for rea in reacts:
	sclist = get_Tshortcut(rea,sclist)

for row in fh:
	if(row.strip() == "#KROME_krates"):
		for x in reacts:
			sTlimit = ""
			if(x.kphrate==None and useTlimits): sTlimit = "if(Tgas."+x.TminOp+"."+x.Tmin+" .and. Tgas."+x.TmaxOp+"."+x.Tmax+")"
			kstr = "\t" + sTlimit + " k("+str(x.idx)+") = " + x.krate + " !" + x.verbatim
			kstr = truncF90(kstr, 60,"*")
			fout.write(truncF90(kstr, 60,"/")+"\n")
	elif(row.strip() == "#KROME_implicit_arrays"):
		fout.write(truncF90(implicit_arrays,60,","))
	elif(row.strip() == "#KROME_masses"):
		for x in specs:
			massrow = "\tget_mass("+str(x.idx)+") = " + str(x.mass).replace("e","d") + "\t!" + x.name + "\n"
			fout.write(massrow.replace("0.0","0.d0"))
	elif(row.strip() == "#KROME_names"):
		for x in specs:
			fout.write("\tget_names("+str(x.idx)+") = \"" + x.name + "\"\n")
	elif(row.strip() == "#KROME_charges"):
		for x in specs:
			fout.write("\tget_charges("+str(x.idx)+") = " + str(x.charge) + ".d0 \t!" + x.name + "\n")
	elif(row.strip() == "#KROME_reaction_names"):
		for x in reacts:
			kstr = "\tget_rnames("+str(x.idx)+") = \"" + x.verbatim +"\""
			fout.write(kstr+"\n")
	elif(row.strip() == "#KROME_Tshortcuts"):
		#print [x.split("=")[0] for x in sclist]
		for shortcut in sclist:
			fout.write(shortcut+"\n")
	elif(row.strip() == "#KROME_header"):
		fout.write(get_licence_header())
	else:
		fout.write(row)
if(not(buildCompact)):
	fout.close()
print "done!"

#********* PHOTO ****************
print "- writing krome_photo.f90...",
fh = open("src/krome_photo.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_photo.f90","w")
phvars = []
pheatvars= []
ph_func = ph_qromos = ph_heat = ph_heat_qromos = ph_zero = ph_heat_print = ""
for react in reacts:
	phstuff = get_ph_stuff(react)
	if(phstuff==None): continue
	ph_func += phstuff["ph_func"]+"\n"
	ph_qromos += phstuff["qromos"]+"\n"
	ph_heat += phstuff["ph_heat"]+"\n"
	ph_name = phstuff["reaname"]

	phvars.append("krome_kph_"+ph_name)
	pheatvars.append("krome_pheat_"+ph_name)

	#string to print computed photoheating values
	ph_heat_print += "print '(a20,E11.3,a1,a6)',\"" + react.verbatim + "\", " + "krome_pheat_"+ ph_name + ",\"\",\"eV/s\"\n"

	#string containing photoheating computations (integrals)
	ph_heat_qromos += "\t" + phstuff["qromos"].replace("sigma_", "heat_").replace("krome_kph_","krome_pheat_") + "\n"

#inizialization of photoionization and photoheating common variables to zero
for x in phvars:
	ph_zero += x + " = 0.d0\n"
for x in pheatvars:
	ph_zero += x + " = 0.d0\n"


skip = False
for row in fh:
	if(row.strip() == "#IFKROME_usePhIoniz" and not(usePhIoniz)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(skip): continue
	#replace krome variables
	if(usePhIoniz):
		row = row.replace("#KROME_photo_functions", ph_func +"\n")
		row = row.replace("#KROME_photo_qromos", ph_qromos +"\n")
		row = row.replace("#KROME_photo_init_zero", ph_zero +"\n")
	if(useHeatingPhoto):
		row = row.replace("#KROME_photo_heating_qromos", ph_heat_qromos +"\n")
		row = row.replace("#KROME_photo_heating_functions", ph_heat +"\n")
		row = row.replace("#KROME_photo_heating_print", ph_heat_print +"\n")


	if(row[0]!="#"): fout.write(row)

if(not(buildCompact)):
	fout.close()
print "done!"


#********* TABS ****************
print "- writing krome_tabs.f90...",
fh = open("src/krome_tabs.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_tabs.f90","w")

skip = False
for row in fh:
	if(row.strip() == "#IFKROME_useCustomCoe" and not(useCustomCoe)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useTabs" and not(useTabs)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useStandardCoe" and ((useCustomCoe) or (useTabs))): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(skip): continue
	row = row.replace("#KROME_logTlow", "ktab_logTlow = log10(max("+str(TminAuto)+",2.73d0))")
	row = row.replace("#KROME_logTup", "ktab_logTup = log10("+str(TmaxAuto)+")")
	if(useCustomCoe): row = row.replace("#KROMEREPLACE_customCoeFunction", customCoeFunction)

	if(row[0]!="#"): fout.write(row)

if(not(buildCompact)):
	fout.close()
print "done!"
#********* DUST ****************
print "- writing krome_dust.f90...",
fh = open("src/krome_dust.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_dust.f90","w")

dustPartnerIdx = dustQabs = dustOptInt = getTdust = ""
if(useDust):
	itype = 0 #dust type index
	#loop in dust types
	for dType in dustTypes:
		itype += 1 #increase index
		dustPartnerIdx += "krome_dust_partner_idx("+str(itype)+") = idx_"+dType+"\n"
		if(useDustT):
			dustQabs += "call init_Qabs(\"opt"+dType+".dat\",dust_opt_Qabs_"+dType
			dustQabs += ",dust_opt_asize_"+dType+",dust_opt_nu_"+dType+")\n"
			dustOptInt += "call dustOptIntegral(dust_opt_Em_"+dType+",dust_opt_Tbb_"+dType+","
			dustOptInt += "dust_opt_asize_"+dType+",&\n dust_opt_nu_"+dType+", dust_opt_Qabs_"+dType+")\n"
			getTdust += "call getTdust(krome_dust_T(nd*("+str(itype-1)+")+1:nd*"+str(itype)
			getTdust += "), dust_opt_Tbb_"+dType+", dust_opt_Em_"+dType+", dust_opt_asize_"+dType+",&\n"
			getTdust += " dust_opt_nu_"+dType+", dust_opt_Qabs_"+dType+")\n"
			getTdust = getTdust.replace("nd*(0)+1","1").replace("nd*1","nd").replace("nd*(1)","nd")

skip = False
for row in fh:
	if(row.strip() == "#IFKROME_useDust" and not(useDust)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(skip): continue

	row = row.replace("#KROME_dustPartnerIndex", dustPartnerIdx)
	row = row.replace("#KROME_init_Qabs", dustQabs)
	row = row.replace("#KROME_opt_integral", dustOptInt)
	row = row.replace("#KROME_getTdust", getTdust)
 
	if(row[0]!="#"): fout.write(row)

if(not(buildCompact)):
	fout.close()
print "done!"

#*********COOLING****************
#write header in krome_cooling.f90
print "- writing krome_cooling.f90...",
fh = open("src/krome_cooling.f90")

if(not(buildCompact)):
	fout = open(buildFolder+"krome_cooling.f90","w")

#create coefficients, flux, and cooling functions for dH cooling
i = 0
dH_varsa = []
dH_coe = dH_cool = ""
if(useCoolingdH):
	for rea in reacts:
		if(rea.dH!=None and rea.dH<0.e0):
			i += 1 #count cooling reactions
			kvar = "k"+str(i) #local variable for coefficient
			dH_varsa.append(kvar) #variables array
			dH_coe += "!"+rea.verbatim+"\n" #reaction comment
			dH_coe += kvar+" = 0.d0\n"
			dH_coe += "if(Tgas."+TlimitOpLow+"."+rea.Tmin+" .and. Tgas."+TlimitOpHigh+"."+rea.Tmax+") then\n"
			dH_coe += kvar+" = "+rea.krate+"\n" #evaluate reation coefficient
			dH_coe += "end if\n\n" #evaluate reation coefficient
			dH_cool += "cool = cool + "+kvar+"*"+("*".join(["n("+x.fidx+")" for x in rea.reactants])) #evautate cooling
			dH_cool += "*"+(str(abs(rea.dH))).replace("e","d")+"\n"


#bremsstrahlung for all the ions as charge**2*n_ion
skip = False
bms_ions = "bms_ions ="
for x in specs:
	charge = x.charge
	if(charge>0):
		mult = ""
		if(charge>1): mult = str(charge*charge)+".d0*"
		bms_ions += " +"+mult+"n("+x.fidx+")"

for row in fh:
	if(row.strip() == "#KROME_header"):
		fout.write(get_licence_header())
	else:
		srow = row.strip()
		#enthalpic
		if(srow == "#IFKROME_useCoolingdH" and (not(useCoolingdH) or len(dH_varsa)==0)): skip = True
		if(srow == "#ENDIFKROME"): skip = False

		#dust
		if(srow == "#IFKROME_useCoolingDust" and not(useCoolingDust)): skip = True
		if(srow == "#ENDIFKROME"): skip = False

		#metals
		if(srow == "#IFKROME_useCoolingZ" and not(useCoolingZ)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZ"): skip = False

		#individual metals
		if(srow == "#IFKROME_useCoolingZC" and not(useCoolingZC)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZC" and useCoolingZ): skip = False
		
		if(srow == "#IFKROME_useCoolingZCp" and not(useCoolingZCp)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZCp" and useCoolingZ): skip = False
		
		if(srow == "#IFKROME_useCoolingZSi" and not(useCoolingZSi)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZSi" and useCoolingZ): skip = False
		
		if(srow == "#IFKROME_useCoolingZSip" and not(useCoolingZSip)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZSip" and useCoolingZ): skip = False

		if(srow == "#IFKROME_useCoolingZO" and not(useCoolingZO)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZO" and useCoolingZ): skip = False
		
		if(srow == "#IFKROME_useCoolingZOp" and not(useCoolingZOp)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZOp" and useCoolingZ): skip = False
		
		if(srow == "#IFKROME_useCoolingZFe" and not(useCoolingZFe)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZFe" and useCoolingZ): skip = False
		
		if(srow == "#IFKROME_useCoolingZFep" and not(useCoolingZFep)): skip = True
		if(srow == "#ENDIFKROME_useCoolingZFep" and useCoolingZ): skip = False


		#CEN
		if(srow == "#IFKROME_useCoolingCEN" and not(useCoolingCEN)): skip = True
		if(srow == "#ENDIFKROME"): skip = False

		#H2
		if(srow == "#IFKROME_useCoolingH2" and not(useCoolingH2)): skip = True
		if(srow == "#ENDIFKROME"): skip = False

		#H2GP92
		if(srow == "#IFKROME_useCoolingH2GP" and not(useCoolingH2GP98)): skip = True
		if(srow == "#ENDIFKROME"): skip = False
		
		#HD
		if(srow == "#IFKROME_useCoolingHD" and not(useCoolingHD)): skip = True
		if(srow == "#ENDIFKROME"): skip = False
		
		#COMPTON
		if(srow == "#IFKROME_useCoolingCompton" and not(useCoolingCompton)): skip = True
		if(srow == "#ENDIFKROME"): skip = False

		#CIE
		if(srow == "#IFKROME_useCoolingCIE" and not(useCoolingCIE)): skip = True
		if(srow == "#ENDIFKROME"): skip = False

		if(skip): continue
		
		if(useH2opacity):
			row = row.replace("#KROME_H2opacity", "* min(1.d0, (1.25d-10 * sum(n(1:nmols)))**(-.45))") #thick case (note that 1.25d-10 = 1/8e9)
		else:
			row = row.replace("#KROME_H2opacity", "") #thin case

		#replace pragma for dH_cooling
		if(useCoolingdH):
			row = row.replace("#KROME_vars","real*8::"+(",".join(dH_varsa))+"\n")
			row = row.replace("#KROME_rates",dH_coe)
			row = row.replace("#KROME_dH_cooling",dH_cool)
		#replace pragma of bremsstrahlung ions
		row = row.replace("#KROME_brem_ions",bms_ions)

		if(row[0]!="#"): fout.write(row)

if(not(buildCompact)):
	fout.close()
print "done!"


#*********HEATING****************
#write header in krome_heating.f90
print "- writing krome_heating.f90...",
fh = open("src/krome_heating.f90")

if(not(buildCompact)):
	fout = open(buildFolder+"krome_heating.f90","w")

#create coefficients, flux, and cooling functions for dH cooling
i = 0
dH_varsa = []
dH_coe = dH_heat = ""
if(useHeatingdH):
	for rea in reacts:
		if(rea.dH!=None and rea.dH>0.e0):
			i += 1 #count heating reactions
			kvar = "k"+str(i) #local variable for coefficient
			dH_varsa.append(kvar) #variables array
			dH_coe += kvar+" = 0.d0\n"
			dH_coe += "if(Tgas."+TlimitOpLow+"."+rea.Tmin+" .and. Tgas."+TlimitOpHigh+"."+rea.Tmax+") then\n"
			dH_coe += kvar+" = "+rea.krate+"\n" #evaluate reation coefficient
			dH_coe += "end if\n\n" #evaluate reation coefficient
			dH_heat += "heat = heat + "+kvar+"*"+("*".join(["n("+x.fidx+")" for x in rea.reactants])) #evautate heating
			dH_heat += "*"+(str(abs(rea.dH))).replace("e","d")+"\n"


#build H2 heating according to the rates
HChem = ""
sclist = []
if(useHeatingChem):
	Rref = []
	Pref = []
	kref = []
	Rref.append(sorted(["H","H","H"]))
	Pref.append(sorted(["H2","H"]))
	kref.append("4.48d0*n(idx_H)**3")
	Rref.append(sorted(["H2","H","H"]))
	Pref.append(sorted(["H2","H2"]))
	kref.append("4.48d0*n(idx_H)**2*n(idx_H2)")
	Rref.append(sorted(["H-","H"]))
	Pref.append(sorted(["H2","E"]))
	kref.append("3.53d0*n(idx_H)*n(idx_Hk)")
	Rref.append(sorted(["H2+","H"]))
	Pref.append(sorted(["H2","H+"]))
	kref.append("1.83d0*n(idx_H)*n(idx_H2j)")
	Rref.append(sorted(["H2","H"]))
	Pref.append(sorted(["H","H","H"]))
	kref.append("-4.48d0*n(idx_H)*n(idx_H2)")
	for rea in reacts:
		R = sorted([x.name for x in rea.reactants])
		P = sorted([x.name for x in rea.products])
		for i in range(len(Rref)):
			if(Rref[i]==R and Pref[i]==P):
				sclist = get_Tshortcut(rea,sclist) #get the shortcuts for temperature
				headchem = "!"+rea.verbatim + "\n"
				tklim = headchem + "if(Tgas." + rea.TminOp + "."  + rea.Tmin + " .and. Tgas." + rea.TmaxOp + "." + rea.Tmax + ") then\n"
				HChem += tklim + "HChem = HChem + ("+rea.krate+") * ("+kref[i] + ")\n end if\n\n"
				break
			


#build heating terms
pheatvars = []
if(usePhIoniz):
	for react in reacts:
		phstuff = get_ph_stuff(react)
		if(phstuff==None): continue
		reaname = phstuff["reaname"]
		reag = react.reactants
		fake_opacity = ""
		if(useFakeOpacity): fake_opacity = " * exp(-n(" + reag[0].fidx + ") / n0)"
		pheatvars.append("krome_pheat_"+reaname + " * n(" + reag[0].fidx + ")" + fake_opacity)


skip = False
for row in fh:
	if(row.strip() == "#KROME_header"):

		fout.write(get_licence_header())
	else:
		if(row.strip() == "#IFKROME_useHeatingdH" and (not(useHeatingdH) or len(dH_varsa)==0)): skip = True
		if(row.strip() == "#ENDIFKROME"): skip = False

		if(row.strip() == "#IFKROME_useHeatingCompress" and not(useHeatingCompress)): skip = True
		if(row.strip() == "#ENDIFKROME"): skip = False

		if(row.strip() == "#IFKROME_useHeatingPhoto" and not(useHeatingPhoto)): skip = True
		if(row.strip() == "#ENDIFKROME"): skip = False

		if(row.strip() == "#IFKROME_useHeatingChem" and not(useHeatingChem)): skip = True
		if(row.strip() == "#ENDIFKROME"): skip = False

		if(skip): continue

		row = row.replace("#KROME_photo_heating", "photo_heating = " + (" &\n+ ".join(pheatvars)))
		row = row.replace("#KROME_HChem_terms", HChem) #replace chemical heating terms
		
		#replace shortcuts for temperature
		if(row.strip() == "#KROME_Tshortcuts"):
			ssc = ""
			for shortcut in sclist:
				ssc += shortcut + "\n"
			row = ssc
		#replace pragma for dH_heating
		if(useHeatingdH):
			row = row.replace("#KROME_vars","real*8::"+(",".join(dH_varsa))+"\n")
			row = row.replace("#KROME_rates",dH_coe)
			row = row.replace("#KROME_dH_heating",dH_heat)
			
		if(len(row)==0): continue
		if(row[0]!="#"): fout.write(row)

if(not(buildCompact)):
	fout.close()
print "done!"


#*********ODE****************
#write parameters in krome_ode.f90
print "- writing krome_ode.f90...",

fh = open("src/krome_ode.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_ode.f90","w")


dustH2 = "nH2dust = 0.d0\n"
if(useDustH2):
	iType = 0
	for dType in dustTypes:
		ilow = nmols + iType * dustArraySize + 1
		iup = nmols + (iType + 1) * dustArraySize
		dustH2 += "nH2dust = nH2dust + krome_H2_dust(n(" + str(ilow) + ":" + str(iup) + ")," 
		dustH2 += " krome_dust_T(" + str(ilow-nmols) + ":" + str(iup-nmols) + "), n(:), H2_eps_"+dType+", vgas)\n"
		iType += 1

skip = False
for row in fh:
	if(row.strip() == "#IFKROME_use_thermo" and not(use_thermo)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_report" and not(doReport)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useDust" and not(useDust)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(skip): continue

	if(row.strip() == "#KROME_ODE"):
		if(use_implicit_RHS):
			fout.write(get_implicit_ode(maxnreag, maxnprod, useTopology or useFlux)+"\n")
		else:
			#add dust ODE and partner specie RHS terms
			if(useDust):
				ndust = dustArraySize*dustTypesSize #number of dust ODEs
				nmols = len(specs)-4-ndust #number of mols ODEs

				#print first dust to sum terms up
				for x in dnw[nmols:nmols+ndust]:
					fout.write("\t" + x + "\n")
				fout.write("\n") #print a blank line

				#print sums for different partners
				iType = 0
				for dType in dustTypes:
					ilow = nmols + iType * dustArraySize + 1
					iup = nmols + (iType + 1) * dustArraySize
					kpart = "krome_dust_partner_ratio(" + str(ilow-nmols) + ":" + str(iup-nmols) + ")"
					fout.write("\tdSumDust"+dType + " = sum(dn(" + str(ilow) + ":" + str(iup) + ")*"+kpart+")\n")
					iType += 1
				fout.write("\n") #print a blank line

				#print mols ODEs and look for dust partners to add summations
				# and H2 formation on dust and H depletion
				idnw = 0
				for x in dnw[:nmols]:
					for dType in dustTypes:
						if(dType==specs[idnw].name): x += " - dSumDust"+dType
					if(useDustH2):
						if("H"==specs[idnw].name): x += " - 2d0*nH2dust"
						if("H2"==specs[idnw].name): x += " + nH2dust"
					fout.write("\t" + x + "\n")
					idnw += 1
				#print other species (CR, PHOTONS, Tgas, dummy)
				for x in dnw[nmols+ndust:]:
					fout.write("\t" + x + "\n")

			#simply write ODEs without dust
			else:
				for x in dnw:
					fout.write("\t" + x + "\n")
	elif(row.strip() == "#KROME_dustSumVariables" and useDust):
		#add partner sum dust variable declarations
		dustSumVar = []
		for dType in dustTypes:
			dustSumVar.append("dSumDust"+dType)
		fout.write("\t real*8::" + (",".join(dustSumVar)) + "\n")
	elif(row.strip() == "#KROME_header"):
		fout.write(get_licence_header())
	elif(row.strip() == "#KROME_implicit_variables"):
		fout.write("real*8::rr\n")
		ris = (",".join(["r"+str(i+1) for i in range(maxnreag)]))
		pis = (",".join(["p"+str(i+1) for i in range(maxnprod)]))
		fout.write("integer::i,"+ris+","+pis+"\n")
	elif(row.strip() == "#KROME_report_flux"):
		report_flux = ("*".join(["n(arr_r"+str(j+1)+"(i))" for j in range(maxnreag)]))
 		fout.write("write(fnum,'(I5,E12.3e3,a2,a50)') i,k(i)*"+report_flux+",'',rnames(i)\n")

	elif(row.strip() == "#KROME_odeConstant" and useODEConstant):
		fout.write("dn(:) = dn(:) "+ODEConstant+" \n")
	elif(row.strip() == "#KROME_odeDust"):
		fout.write("dn(:) =  krome_dust \n")
	elif(row.strip() == "#KROME_dust_H2"):
		fout.write(dustH2+"\n")
	elif(row.strip() == "#KROME_JAC_PD"):
		if(solver_MF==222):
			fout.write("\n")
		else:
			#J(i,j) = df_i/dx_j
			for i in range(neq):
				if(i==0): fout.write("if(j=="+str(i+1)+") then\n")
				if(i>0): fout.write("elseif(j=="+str(i+1)+") then\n")
				if(i!=Tgas_species.idx-1):
					spdj = ""
					has_pdj = False
					for j in range(neq):
						if(jsparse[j][i]==1):
							has_pdj = True
							spdj += ("\t" + jac[j][i] + "\n")
					#if(has_pdj): fout.write("k(:) = coe_tab(n(:))\n")
					fout.write(spdj)
				else:
					jacT = """!rough estimate for d^2T/dt/dx_i
						do i=1,neq-1
							if(n(idx_Tgas)-jac_nold(idx_Tgas).ne.0.d0) then
								pdj(i) = (jac_dnold(i) - jac_dn(i))/(jac_nold(idx_Tgas) - n(idx_Tgas))
							end if
						end do"""
					if(not(use_thermo)): jacT = ""
					fout.write("\t" + jacT.replace("\t","") + "\n")
			fout.write("end if\n")
	elif(row.strip() == "#KROME_gamma"):
		#computes the adiabatic index if needed or uses a user-defined expression 
		if(typeGamma=="DEFAULT"):
			gamma = "1.66666666667d0" #default gamma is 5/3
		elif(typeGamma=="FULL"):
			specsGamma = ["H","HE","E","H2"] #species used in the gamma
			gammaNm = []
			gammaDm = []
			gammaNb = []
			gammaDb = []
			#loop on species
			for mol in specs:
				if(mol.name.upper() in specsGamma):
					nfidx = "n("+mol.fidx+")" #number density
					if(mol.is_atom): #monoatomic
						gammaNm.append(nfidx)
						gammaDm.append(nfidx)
					else: #diatomic
						gammaNb.append(nfidx)
						gammaDb.append(nfidx)
			#build fortran expression for gamma (see Grassi et al. 2011)
			gammaN = "(5.d0*("+(" + ".join(gammaNm)) + ") + 7.d0*("+(" + ".join(gammaNb)) + "))"
			gammaD = "(3.d0*("+(" + ".join(gammaDm)) + ") + 5.d0*("+(" + ".join(gammaDb)) + "))"
			gamma = gammaN + " / &\n" +gammaD
		else: 
			#user-defined gamma
			gamma = typeGamma
		#write gamma
		fout.write("krome_gamma = " + gamma + "\n")
			
	else:
		srow = row.strip()
		if(len(srow)>0):
			if(srow[0]!="#"): fout.write(row)
		else:
			fout.write(row)
if(not(buildCompact)):
	fout.close()
print "done!"

#*********USER****************
#write parameters in krome_user.f90
print "- writing krome_user.f90...",

fh = open("src/krome_user.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_user.f90","w")
skip = False

solar = {
	#"He":"9.749177d-2",
	"O":"5.241966d-4",
	"C":"3.582559d-4",
	"N":"1.120923d-4",
	"Ne":"1.098945d-4",
	"Si":"3.296834d-5",
	"Mg":"3.077045d-5",
	"Fe":"2.967150d-5",
	"Si":"1.758311d-5",
	"Ne":"1.648417d-5",
	#"D":"1.648417d-5",
	"Ca":"2.197889d-6"
	}

scaleZ = []
for (k,v) in solar.iteritems():
	for mols in specs:
		if(k.upper()==mols.name.upper()):
			scaleZ.append("n("+mols.fidx+") = max(n(idx_H) * 1d1**(Z+log10("+str(v)+")), 1d-40)")

for row in fh:

	srow = row.strip()
	if(srow == "#IFKROME_use_cooling" and not(use_cooling)): skip = True
	if(srow == "#ENDIFKROME"): skip = False
	if(skip): continue

	if(srow == "#KROME_species"):
		for x in specs:
			fout.write("\tinteger,parameter::" + "KROME_"+x.fidx + " = " + str(x.idx) +"\t!"+x.name+"\n")
	elif(srow == "#KROME_header"):
		fout.write(get_licence_header())
	elif(srow == "#KROME_scaleZ"):
		fout.write(("\n".join(scaleZ))+"\n")
	else:
		if(len(srow)>0):
			if(srow[0]!="#"): fout.write(row)
		else:
			fout.write(row)
if(not(buildCompact)):
	fout.close()
print "done!"


#********* REDUCTION ****************
print "- writing krome_reduction.f90...",
fh = open("src/krome_reduction.f90")
if(not(buildCompact)):
	fout = open(buildFolder+"krome_reduction.f90","w")
skip = False
for row in fh:
	srow = row.strip()
	if(srow == "#IFKROME_useTopology" and not(useTopology)): skip = True
	if(srow == "#ENDIFKROME"): skip = False
	if(srow == "#IFKROME_useFlux" and not(useFlux)): skip = True
	if(srow == "#ENDIFKROME"): skip = False
	if(srow == "#IFKROME_useReduction" and not(useTopology) and not(useFlux)): skip = True
	if(srow == "#ENDIFKROME"): skip = False

	if(skip): continue
	if(srow == "#KROME_rvars"):
		fout.write("integer::"+(",".join(["r"+str(j+1) for j in range(maxnreag)]))+"\n")
	if(srow == "#KROME_arrs"):
		for j in range(maxnreag):
			fout.write("r"+str(j+1)+" = arr_r"+str(j+1)+"(i)\n")
	if(srow == "#KROME_arr_flux"):
		fout.write("arr_flux(i) = k(i)*"+("*".join(["n(r"+str(j+1)+")" for j in range(maxnreag)]))+"\n")

	if(row[0]!="#"): fout.write(row)
if(not(buildCompact)):
	fout.close()

print "done!"


#*********MAIN****************
#write WORKS arrays and IAC/JAC in krome.f90
print "- writing krome.f90...",
if(useDvodeF90):
	fh = open("src/kromeF90.f90")
else:
	fh = open("src/krome.f90")

if(is_number(ATOL)): ATOL = '%e' % ATOL
if(is_number(RTOL)): RTOL = '%e' % RTOL
ATOL = ATOL.replace("e","d")
RTOL = RTOL.replace("e","d")

if(not(buildCompact)):
	fout = open(buildFolder+"krome.f90","w")
skip = False
for row in fh:
	if(row.strip() == "#IFKROME_useX" and not(useX)): skip = True
	if(row.strip() == "#ELSEKROME" and not(useX)): skip = False
	if(row.strip() == "#ELSEKROME" and useX): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useTabs" and not(useTabs)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useFlux" and not(useFlux)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_report" and not(doReport)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useTopology" and not(useTopology)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_check_mass_conservation" and not(checkConserv)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useDust" and not(useDust)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(row.strip() == "#IFKROME_useEquilibrium" and not(useEquilibrium)): skip = True
	if(row.strip() == "#ENDIFKROME"): skip = False

	if(useDust):
		row = row.replace("#KROME_dust_arguments",",xdust")
	else:
		row = row.replace("#KROME_dust_arguments","")

	row = row.replace("#KROME_ATOL",str(ATOL))
	row = row.replace("#KROME_RTOL",str(RTOL))

	if(skip): continue

	if(row.strip() == "#KROME_header"):
		fout.write(get_licence_header())
	elif(row.strip() == "#KROME_rwork_array"):
		fout.write("\treal*8::rwork("+str(lrw)+")\n")
	elif(row.strip() == "#KROME_iwork_array"):
		fout.write("\tinteger::iwork("+str(30+len(ia)+len(ja))+")\n")
	elif(row.strip() == "#KROME_init_IAC"):
		fout.write("\t"+iaf+"\n")
	elif(row.strip() == "#KROME_init_JAC"):
		fout.write("\t"+jaf+"\n")
	elif(row.strip() == "#KROME_MF"):
		if(solver_MF==21):
			fout.write("\tMF=21\n")
		elif(solver_MF==222):
			fout.write("\tMF=222\n")
	else:
		if(row[0]!="#"): fout.write(row)
if(not(buildCompact)):
	fout.close()
print "done!"


if(buildCompact): fout.close()

#*********REPORT.gps****************
#write gnuplot script to plot abundances evolution
if(doReport):
	fout = open(buildFolder+"report.gps","w")
	fout.write("#plot KROME report\n")
	fout.write("set logscale\n")
	fout.write("set xlabel \"log(time/s)\"\n")
	fout.write("plot 'fort.98' u 1:2 w l t \""+specs[0].name+"\",\\\n")
	for i in range(neq-2):
		fout.write("'' u 1:"+str(i+3)+" w l t \""+specs[i+1].name+"\",\\\n")
	fout.write("'' u 1:"+str(neq+2)+" w l t \""+specs[neq-1].name+"\"\n")
	fout.close()

#*********************************
#*********************************
#*********************************
#copy other files to build
print "- copying others...",

#copy static files to build
if(is_test):
	print "- copying test to /build...",
	if(useDvodeF90):
		shutil.copyfile("tests/"+test_name+"/MakefileF90", buildFolder+"Makefile")
	elif(buildCompact):
		shutil.copyfile("tests/"+test_name+"/MakefileCompact", buildFolder+"Makefile")
	else:
		if(pedanticMakefile):
			shutil.copyfile("tests/Makefile_pedantic", buildFolder+"Makefile")
		else:
			shutil.copyfile("tests/"+test_name+"/Makefile", buildFolder+"Makefile")

	test_file = "tests/"+test_name+"/test.f90"
	plot_file = "tests/"+test_name+"/plot.gps"
	#chech if test file exists

	if(not(os.path.isfile(filename))): die("ERROR: Test file \""+test_file+"\" doesn't exist!")

	shutil.copyfile(test_file, buildFolder+"test.f90")
	if(has_plot): shutil.copyfile(plot_file, buildFolder+"plot.gps")
	print " done!"

#copy solver files to build
print "- copying solver to /build...",
if(useDvodeF90):
	shutil.copyfile("solver/dvode_f90_m.f90", buildFolder+"dvode_f90_m.f90")
else:
	shutil.copyfile("solver/opkdmain.f", buildFolder+"opkdmain.f")
	shutil.copyfile("solver/opkda1.f", buildFolder+"opkda1.f")
	shutil.copyfile("solver/opkda2.f", buildFolder+"opkda2.f")
print " done!"

#copy dust optical properties to build/
if(useDustT):
	for dType in dustTypes:
		shutil.copyfile("data/opt"+dType+".dat", buildFolder+"opt"+dType+".dat")
	

print
print "indent...",
if(doIndent):
	if(buildCompact):
		indentF90(buildFolder+"krome_all.f90")
	else:
		indentF90(buildFolder+"krome_commons.f90")
		indentF90(buildFolder+"krome_constants.f90")
		indentF90(buildFolder+"krome_cooling.f90")
		indentF90(buildFolder+"krome_heating.f90")
		indentF90(buildFolder+"krome_dust.f90")
		indentF90(buildFolder+"krome.f90")
		indentF90(buildFolder+"krome_ode.f90")
		indentF90(buildFolder+"krome_photo.f90")
		indentF90(buildFolder+"krome_reduction.f90")
		indentF90(buildFolder+"krome_subs.f90")
		indentF90(buildFolder+"krome_tabs.f90")
		indentF90(buildFolder+"krome_user.f90")

print "done!"

print
print "You'll find the necessary files in "+buildFolder
print "Example call to the solver in "+buildFolder+"test.f90"
print "Example Makefile in "+buildFolder+"Makefile"

#check for large reaction set
if(len(reacts)>500 and not(use_implicit_RHS)):
	print
	print "WARNING: "+str(len(reacts))+" reactions found! Using implicit RHS (option -iRHS) could be more efficient"
	print "  and also allows faster compilation."

print
if(not(is_test)):
	print "Call KROME in your code as:"
	if(useX):
		print "    call krome(x(:), gas_density, gas_temperature, time_step)"
	else:
		print "    call krome(x(:), gas_temperature, time_step)"
	print "where:" 
	print " x(:) is a real*8 array of size "+str(len(specs)-4)+(" of the mass fractions" if useX else " of number densities [1/cm3]")
	if(useX): print " gas_density  is the gas density in [g/cm3]"
	print " gas_temperature is the gas temperature in [K]"
	print " time_step is the integration time-step in [s]"

	fout = open(buildFolder+"test.f90","w")
	fout.write(get_example(len(specs)-4,useX))
	fout.close()
	indentF90(buildFolder+"test.f90")
	if(buildCompact):
		shutil.copyfile("tests/MakefileCompact", buildFolder+"Makefile")
	else:
		if(pedanticMakefile):
			shutil.copyfile("tests/Makefile_pedantic", buildFolder+"Makefile")
		else:
			shutil.copyfile("tests/Makefile", buildFolder+"Makefile")

else:
	print "This is a test. To run it just type:"
	print "> cd build/"
	print "> make"
	print "> ./krome"
print
print "Everything done, goodbye!"


get_quote()

