#!/usr/bin/python
#!python
import sys
from kromelib import *
from kromeobj import *

argv = sys.argv

#create the KROME object
krome = krome()

#init argaprser
krome.init_argparser()

#search argv for tests
krome.select_test(argv)

#read argv options
krome.argparsing(argv)

#read thermochemistry data from file
krome.load_thermochemistry()

#prepares mass and species dictionaries
krome.prepare_massdict()

#read reaction file
krome.read_file()

#compute reverse kinetics if necessary
krome.do_reverse()

#add metals if cooling is selected
krome.addMetals()

#add a minimum value to reactions
krome.addReaMin()

#compute enthalpy of reactions if necessary
krome.computeEnthalpy()

#add the dust if selected
krome.addDust()

#add the dust temperature
krome.addDustT()

#add special species (e.g. dummy)
krome.addSpecial()

#count species, dust, ecc...
krome.countSpecies()

#dump reactions and species to a file
krome.dumpNetwork()

#show ODE stats
krome.showODE()

#create ODE differentials
krome.createODE()

#create Jacobian
krome.createJAC()

#create sparsity structure
krome.IACJAC()

#compute solver parameters
krome.solverParams()

#prepare build directory
krome.prepareBuild()

#replace pragma from src files
krome.makeCommons()
krome.makeConstants()
krome.makeUserCommons()
krome.makeSubs()
krome.makePhoto()
krome.makeTabs()
krome.makeDust()
krome.makeCooling()
krome.makeHeating()
krome.makeODE()
krome.makeUser()
krome.makeReduction()
krome.makeMain()

#create a gnuplot script for report
krome.makeReport()

#copy other files
krome.copyOthers()

#indent all the f90 files
krome.indent()

#print a final report and usage hints
krome.final_report()

#write a random quote
get_quote()

