#File to generate multiplicative factors by which cooling due to a given chemical species
#should be reduced at high redshifts due to CMB photons providing heating to the species
#Generated using Despotic by Piyush Sharda in 2025 (sharda@strw.leidenuniv.nl)

from joblib import Parallel, delayed
from tqdm import tqdm
import numpy as np

import despotic
from despotic import cloud

import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

#joblib ignores the above setting when using multiple threads
import os
os.environ['PYTHONWARNINGS']='ignore'

c = cloud(fileName='cloudfiles/MilkyWayGMC.desp',verbose=False)
c.noWarn = True

sp = str(input('enter specie name: '))
LTE = bool(input('For LTE, type 1. For NLTE, just press enter: ')) #not all species will converge at all (nH,Tg) under NLTE. One can play around with tolerances or reduced the number of transitions being solved for to make NLTE calculations possible for a larger subset of models.

print('LTE Selected: ', LTE)

#z = np.array([0,1,2,3,4,5,6,7,8,10,12,15,20,30])
#nH_1 = np.logspace(-2, 2, 5, endpoint=False)
#nH_2 = np.logspace(2,7,20, endpoint=False)
#nH_3 = np.logspace(7, 14, 5)
#nH = np.concatenate((nH_1, nH_2, nH_3))
#Tg = np.array([3.0, 5.460e+00, 8.190e+00, 1.092e+01, 1.365e+01, 1.638e+01, 1.911e+01, 2.184e+01, 
#	2.457e+01, 3.003e+01, 3.549e+01, 4.368e+01, 5.000e+01, 5.733e+01, 6.000e+01, 8.463e+01, 1.000e+02, 
#	1.500e+02, 3.000e+02, 1.000e+03, 3.000e+03, 1.000e+04])

z = np.linspace(0,200,201)

if sp == 'co':
    nH = np.logspace(-2, 14, 201)
    #nH = np.array([1e4])
    #Tg1 = np.logspace(np.log10(3.0), 4, 31)
    Tg2 = 2.73*(1+z)
    Tg = Tg2 #np.sort(np.concatenate((Tg1, Tg2)))
    msp = 28
elif sp == 'c':
    nH = np.logspace(-2, 14, 31)
    Tg = np.logspace(np.log10(3.0), 4, 31)
    msp = 12
elif sp == 'c+':
    nH = np.logspace(-2, 14, 31)
    Tg = np.logspace(np.log10(3.0), 4, 31)
    msp = 12
elif sp == 'oh':
    nH = np.logspace(2, 12, 31)
    Tg = np.logspace(1, 3, 31)
    msp = 17
elif sp == 'oh2o':
    nH = np.logspace(-2, 14, 31)
    Tg = np.logspace(np.log10(3.0), 4, 31)
    msp = 18
else:
    raise ValueError('Species not yet supported')

vth = np.sqrt(2*1.38e-16*Tg/(msp*1.67e-24))
sigmav = vth

total = len(z) * len(nH) * len(Tg)
print('Total models to run: ', total, len(z), len(nH), len(Tg))

if LTE:
    filename = "cool"+sp.upper()+"_scalefactor_redshift_LTE.dat"
else:
    filename = "cool"+sp.upper()+"_scalefactor_redshift_NLTE.dat"

with open(filename, "w") as f, tqdm(total=total, desc="Running models for "+sp.upper()) as pbar:

    f.write(
        "# This file contains the table for "+sp.upper()+" cooling \n"
        "# scaling factors as a function of redshift \n"
        "# Generated by Piyush Sharda in 2025 using Despotic \n"
        "# The first three columns are the positions in the arrays \n"
        "# The 4th is the redshift \n"
        "# The 5th is log10(nH/cm^-3) \n"
        "# The 6th is log10(Tgas/K) \n"
        "# The last is the scaling factor to be multiplied to "+sp.upper()+" cooling \n"
        "# Note that the scaling factors for this file are calculated under LTE = "+str(LTE)+"\n\n"
    )


    # --- Step 1: Compute reference values at z=0 (serial) ---
    lambda_ref = np.zeros((len(nH), len(Tg)))
    for j in range(len(nH)):
        c.nH = nH[j]
        for k in range(len(Tg)):
            c.Tg = Tg[k]
            c.sigmaNT = sigmav[k]

            rhogas = 2.33*1.67e-24*nH[j]
            jeans_length = np.sqrt(np.pi*1.380648e-16*Tg[k]/rhogas/1.67e-24/6.674e-8/2.33)
            NH = 0.5*nH[j]*jeans_length
            c.colDen = NH
            try:
                lambda_ref[j][k] = np.log10(c.dEdt(LTE=LTE)['LambdaLine'][sp])
            except:
                lambda_ref[j][k] = -1e99
            pbar.update(1)

            # write reference row
            f.write('%d \t %d \t %d \t %.8e \t %.8e \t %d \t %.8e \n'%
                    (k+1, j+1, 1, np.log10(Tg[k]), np.log10(nH[j]), 0, lambda_ref[j][k]/lambda_ref[j][k]))
        f.write("\n")

    #'''
    # --- Step 2: Parallelize computation for z > 0 ---
    def run_model(i, j, k):
        """Compute lambdaCO normalized to z=0 for given z, nH, Tg"""
        c.rad.TCMB = 2.73*(1 + z[i])
        c.rad.TradDust = 2.73*(1 + z[i])
        c.nH = nH[j]
        c.Tg = Tg[k]
        c.sigmaNT = sigmav[k]

        rhogas = 2.33*1.67e-24*nH[j]
        jeans_length = np.sqrt(np.pi*1.380648e-16*Tg[k]/rhogas/1.67e-24/6.674e-8/2.33)
        NH = 0.5*nH[j]*jeans_length
        c.colDen = NH
        try:
            lambdaLine = np.log10(c.dEdt(LTE=LTE)['LambdaLine'][sp])
        except:
            lambdaLine = -1e99

        # normalize
        lambdaLine = (10**lambdaLine) / (10**lambda_ref[j][k])
        return i, j, k, lambdaLine

    results = Parallel(n_jobs=-1, backend="loky")(
        delayed(run_model)(i, j, k) for i in range(1, len(z)) for j in range(len(nH)) for k in range(len(Tg))
    )

    # --- Step 3: Write results with progress bar ---
    for i, j, k, lambdaLine in results:
        f.write('%d \t %d \t %d \t %.8e \t %.8e \t %d \t %.8e \n'%
                (k+1, j+1, i+1, np.log10(Tg[k]), np.log10(nH[j]), z[i], lambdaLine))
        if k == len(Tg)-1:
            f.write("\n")
        pbar.update(1)

    #'''

#'''
def clean_dat_file(filename):
    # Read file
    with open(filename, "r") as f:
        data = f.read()

    # Replace values
    data = data.replace("nan", "0e0")
    data = data.replace("inf", "1e0")

    # Write back
    with open(filename, "w") as f:
        f.write(data)

print('Cleaning the datafile to replace inf by 1e0 and nan by 0e0')
print('Finished!')

clean_dat_file(filename)
#'''



